$(function(){
	translate()
})

function translate (){
	$('.language-options li button').on('click', function(){

		var activeLanguage = $(this).text()

		if(activeLanguage === 'Español'){
			$('.slogan').text('Todos los idiomas del mundo, para todos.')
			$('#summary').text('Wikitongues es un esfuerzo comunitario para que todas las personas puedan acceder a las 7.000 lenguas que existen y también las historias y los sentimientos detrás de ellas. Coordinados con una red de voluntarios, nos dedicamos a enseñar al mundo el verdadero significado de diversidad.')
			$('.mobile-text').text('Wikitongues es un esfuerzo comunitario para que todas las personas puedan acceder a las 7.000 lenguas que existen y también las historias y los sentimientos detrás de ellas. Coordinados con una red de voluntarios, nos dedicamos a enseñar al mundo el verdadero significado de diversidad.')
			$('#get-involved').text('Involúcrate.')
			$('.first').text('Hecho con amor internacional por ')
			$('.second').text(' y')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Todos los derechos reservados.')
			$('#name').attr('placeholder','¿Cómo te llamas?')
			$('#email').attr('placeholder','¿Qué es tu correo electrónico?')
			$('#message').attr('placeholder','¿Qué tal?')
			$('#submit').attr('value','Enviar')
		} else if (activeLanguage === 'Català') {
			$('.slogan').text('Tots els idiomes del món, per a tothom.')
			$('#summary').text('Wikitongues és un esforç comunitari perquè totes les persones puguin accedir a les 7.000 llengües que existeixen i també les històries i els sentiments darrere d\'elles. Coordinats amb una xarxa de voluntaris, ens dediquem a ensenyar al món el veritable significat de diversitat.')
			$('.mobile-text').text('Wikitongues és un esforç comunitari perquè totes les persones puguin accedir a les 7.000 llengües que existeixen i també les històries i els sentiments darrere d\'elles. Coordinats amb una xarxa de voluntaris, ens dediquem a ensenyar al món el veritable significat de diversitat.')
			$('#get-involved').text('Involucra\'t.')
			$('.first').text('Fet amb amor internacional per ')
			$('.second').text(' i')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Tots els drets reservats.')
			$('#name').attr('placeholder','Com et dius?')
			$('#email').attr('placeholder','Què es el teu mail?')
			$('#message').attr('placeholder','Què tal?')
			$('#submit').attr('value','Enviar')
		} else if (activeLanguage === 'Italiano') {
			$('.slogan').text('Ogni lingua del mondo, per tutti.')
			$('#summary').text('Wikitongues è una comunità che prova a dare accesso a tutte le persone del mondo a tutte le 7.000 lingue del mondo — storie e sentimenti nascosti dietro ognuna. Con l\'aiuto di una rete di volontari, ci dedichiamo a mostrare al mondo il vero significato di diversità.')
			$('.mobile-text').text('Wikitongues è una comunità che prova a dare accesso a tutte le persone del mondo a tutte le 7.000 lingue del mondo — storie e sentimenti nascosti dietro ognuna. Con l\'aiuto di una rete di volontari, ci dedichiamo a mostrare al mondo il vero significato di diversità.')
			$('#get-involved').text('Resta coinvolto.')
			$('.first').text('Fatto con amore internazionale da ')
			$('.second').text(' e')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Tutti i diritti riservati.')
			$('#name').attr('placeholder','Qual è il tuo nome?')
			$('#email').attr('placeholder','Qual è il tuo indirizzo email?')
			$('#message').attr('placeholder','Il tuo messaggio?')
			$('#submit').attr('value','Inviare')
		} else if (activeLanguage === 'Deutsch') {
			$('.slogan').text('Jede Sprache der Welt, für alle.')
			$('#summary').text('Wikitongues ist eine Gemeinschaft deren Anstrengung es ist den Menschen in der Welt Zugang zu allen 7000 Sprachen in der Welt zu geben - die Geschichte und die Gefühle dahinter. In Zusammenarbeit mit einem Netzwerk von Freiwilligen bemühen wir uns der Welt die wahre Bedeutung von Diversität zu zeigen.')
			$('.mobile-text').text('Wikitongues ist eine Gemeinschaft deren Anstrengung es ist den Menschen in der Welt Zugang zu allen 7000 Sprachen in der Welt zu geben - die Geschichte und die Gefühle dahinter. In Zusammenarbeit mit einem Netzwerk von Freiwilligen bemühen wir uns der Welt die wahre Bedeutung von Diversität zu zeigen.')
			$('#get-involved').text('Mach mit!')
			$('.first').text('Mit internationaler Liebe gemacht ')
			$('.second').text(' und')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('All Rights Reserved.')
			$('#name').attr('placeholder', 'Wie ist Ihr Name?')
			$('#email').attr('placeholder','Was ist Ihre E-Mail?')
			$('#message').attr('placeholder','Wie geht\'s?')
			$('#submit').attr('value','Senden')
		} else if (activeLanguage === 'עברית') {
			$('.slogan').text('כל שפה בעולם, לכולם.')
			$('#summary').text('Wikitongues הינו מאמץ קהילתי שמטרתו לאפשר לכל אדם בעולם גישה לכל 7,000 השפות הקיימות בעולם – הסיפורים והרגש שעומד מאחוריהם. בתיאום עם קהילת מתנדבים, אנחנו מחוייבים להראות לעולם את משמעותו האמיתי של הגִּוּוּן.')
			$('.mobile-text').text('Wikitongues הינו מאמץ קהילתי שמטרתו לאפשר לכל אדם בעולם גישה לכל 7,000 השפות הקיימות בעולם – הסיפורים והרגש שעומד מאחוריהם. בתיאום עם קהילת מתנדבים, אנחנו מחוייבים להראות לעולם את משמעותו האמיתי של הגִּוּוּן.')
			$('#get-involved').text('הצטרפו אלינו.')
			$('.first').text('נעשה באהבה ')
			$('.second').text(' ו -')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('כל הזכויות שמורות.')
			$('#name').attr('placeholder','מה שמך?')
			$('#email').attr('placeholder','מה הדוא"ל שלך?')
			$('#message').attr('placeholder','מה קורה?')
			$('#submit').attr('value','מה קורה?')
		} else if (activeLanguage === 'العربية') {
			$('.slogan').text('أي لغة في العالم هي لغة للجميع و')
			$('#summary').text('ويكي تونق هي مجموعة تسعي لمنح كل الناس في العالم امكانية التعرف علي كل لغات العالم و هي سبعة الف لغة \(7000\) و ما ورائها من قصص و احاسيس بالتنسيق مع مجموعة من المتطوعين نحن نركز علي تعريف العالم بالمعني الحقيقي للتنوع')
			$('.mobile-text').text('ويكي تونق هي مجموعة تسعي لمنح كل الناس في العالم امكانية التعرف علي كل لغات العالم و هي سبعة الف لغة \(7000\) و ما ورائها من قصص و احاسيس بالتنسيق مع مجموعة من المتطوعين نحن نركز علي تعريف العالم بالمعني الحقيقي للتنوع')
			$('#get-involved').text('الانضمام إلينا.')
			$('.first').text('شارك و نظم بواسطة ')
			$('.second').text(' ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />لويكي تونق')
			$('footer p:last-child').text('جميع الحقوق محفوظة')
			$('#name').attr('placeholder','ما اسمك?')
			$('#email').attr('placeholder','ما هو بريدك الإلكتروني؟?')
			$('#message').attr('placeholder','ما الأمر؟?')
			$('#submit').attr('value','إرسال?')
		} else if (activeLanguage === 'Português') {
			$('.slogan').text('Todos as línguas do mundo, para todos.')
			$('#summary').text('Wikitongues é uma comunidade que se esforça para proporcionar à todas as pessoas do mundo o acesso a todas as 7.000 línguas — as histórias e os sentimentos por trás delas. Em conjunto de uma rede de voluntários, nós nos dedicamos para mostrar ao mundo o verdadeiro significado da diversidade.')
			$('.mobile-text').text('Wikitongues é uma comunidade que se esforça para proporcionar à todas as pessoas do mundo o acesso a todas as 7.000 línguas — as histórias e os sentimentos por trás delas. Em conjunto de uma rede de voluntários, nós nos dedicamos para mostrar ao mundo o verdadeiro significado da diversidade.')
			$('#get-involved').text('Envolva-se.')
			$('.first').text('Feito com amor internacional por ')
			$('.second').text(' e')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Todos os direitos reservados.')
			$('#name').attr('placeholder','Qual é o seu nome?')
			$('#email').attr('placeholder','Qual é o seu email?')
			$('#message').attr('placeholder','Qual é a sua mensagem?')
			$('#submit').attr('value','Enviar')
		} else if (activeLanguage === 'Русский') {
			$('.slogan').text('Каждый язык в мире для всех.')
			$('#summary').text('Wikitongues является результатом коллективного усилия дать всем людям в мире доступ к 7000 языкам мира - к их историям и чувствам, стоящими за ними. Работая с сетью добровольцов, мы стремимся показать миру истинное значение разнообразия.')
			$('.mobile-text').text('Wikitongues является результатом коллективного усилия дать всем людям в мире доступ к 7000 языкам мира - к их историям и чувствам, стоящими за ними. Работая с сетью добровольцов, мы стремимся показать миру истинное значение разнообразия.')
			$('#get-involved').text('Примите участие.')
			$('.first').text('Организаторы ')
			$('.second').text(' и')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Все права защищены.')
			$('#name').attr('placeholder','как вас зовут?')
			$('#email').attr('placeholder','электронный адрес?')
			$('#message').attr('placeholder','как дела?')
			$('#submit').attr('value','послать')
		} else if (activeLanguage === 'Afrikaans') {
			$('.slogan').text('Elke taal in die wêreld, vir almal.')
			$('#summary').text("Wikitongues is 'n gemeenskaps inisiatief om aan al die mense in die wêreld toegang te gee tot al 7000 wêreldtale asook die stories en emosies daaragter. In samewerking met 'n netwerk van vrywilligers is ons toegewyd om aan die wêreld die betekenis en verskeidenheid van tale uit te beeld.")
			$('.mobile-text').text("Wikitongues is 'n gemeenskaps inisiatief om aan al die mense in die wêreld toegang te gee tot al 7000 wêreldtale asook die stories en emosies daaragter. In samewerking met 'n netwerk van vrywilligers is ons toegewyd om aan die wêreld die betekenis en verskeidenheid van tale uit te beeld.")
			$('#get-involved').text('Raak betrokke')
			$('.first').text('Gemaak met internasionale liefde deur ')
			$('.second').text(' en')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Alle regte voorbehou.')
			$('#name').attr('placeholder','Wat is jou naam?')
			$('#email').attr('placeholder','Wat is jou e-pos adres?')
			$('#message').attr('placeholder','Hoe lyk dinge?')
			$('#submit').attr('value','Stuur')
		} else if (activeLanguage === '日本語') {
			$('.slogan').text('世界中の言語を、世界中の人々に。')
			$('#summary').text("ウィキタングス（wikitongues）は、世界で話されている７０００言語と、その裏にある物語や想いへのアクセスを世界中の人々に提供することを目指すコミュニティ活動です。ボランティアのネットワークと協力し、多様性の真の意味を世界に提示しようと尽力しています。")
			$('.mobile-text').text("ウィキタングス（wikitongues）は、世界で話されている７０００言語と、その裏にある物語や想いへのアクセスを世界中の人々に提供することを目指すコミュニティ活動です。ボランティアのネットワークと協力し、多様性の真の意味を世界に提示しようと尽力しています。")
			$('#get-involved').text('あなたも参加しませんか。')
			$('.first').text('Made with international love by')
			$('.second').text(' and')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('All Rights Reserved.')
			$('#name').attr('placeholder','名前はなんですか？')
			$('#email').attr('placeholder','メールアドレスはなんですか？')
			$('#message').attr('placeholder','あなたの最近の様子や興味関心を教えてください。')
			$('#submit').attr('value','提出する')
		} else if (activeLanguage === '한국어') {
			$('.slogan').text('모두를 위한 전 세계의 언어')
			$('#summary').text("Wikitongues는 세계 모든 사람들에게 이야기와 감성으로 7000개의 전세계 언어를 접할 수 있는 기회를 마련해줄 공동체 프로젝트입니다. 많은 자원 봉사자와 함께 우리는 세상에 다양성의 진정한 의미를 알리기 위해 최선을 다 할 것입니다.")
			$('.mobile-text').text("Wikitongues는 세계 모든 사람들에게 이야기와 감성으로 7000개의 전세계 언어를 접할 수 있는 기회를 마련해줄 공동체 프로젝트입니다. 많은 자원 봉사자와 함께 우리는 세상에 다양성의 진정한 의미를 알리기 위해 최선을 다 할 것입니다.")
			$('#get-involved').text('여러분도 함께 참여하세요')
			$('.first').text('의 국제 사랑으로 만들었습니다. ')
			$('.second').text(' 하고')
			$('footer p:first-child').html('© 2014년 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('모든 권리는 보호됩니다.')
			$('#name').attr('placeholder','이름이 뭐예요?')
			$('#email').attr('placeholder','이메일 주소가 뭐에요?')
			$('#message').attr('placeholder','잘 지내세요?')
			$('#submit').attr('value','보내기')
		} else if (activeLanguage === 'isiZulu') {
			$('.slogan').text('Izilimi zawowonke umuntu emhlabeni jikelele.')
			$('#summary').text("Inhloso ye-Wikitongues ukwazisa abantu  ngezilimi ezingu-7000 ezikhulunywayo emhlabani jikelele - ngokufaka imizwa nezindaba ezihambelana nalezizilimi.Ukuze siphumelele sisebenzisana nabantu abazinikela mahhala (abavolon’thiyayo) ukuze sikhombise umhlaba ukusebenzisana kwabantu bezizwe ezahlukene.")
			$('.mobile-text').text("Inhloso ye-Wikitongues ukwazisa abantu  ngezilimi ezingu-7000 ezikhulunywayo emhlabani jikelele - ngokufaka imizwa nezindaba ezihambelana nalezizilimi.Ukuze siphumelele sisebenzisana nabantu abazinikela mahhala (abavolon’thiyayo) ukuze sikhombise umhlaba ukusebenzisana kwabantu bezizwe ezahlukene.")
			$('#get-involved').text('Woza nawe.')
			$('.first').text('Made with international love by')
			$('.second').text(' and')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('All Rights Reserved.')
			$('#name').attr('placeholder','Ubani igama lakho?')
			$('#email').attr('placeholder','Sicela I-email yakho?')
			$('#message').attr('placeholder','Unjani namhlanje?')
			$('#submit').attr('value','Thumela.')
		} else if (activeLanguage === 'Ελληνικά') {
			$('.slogan').html('Κάθε γλώσσα του κόσμου, για όλους.')
			$('#summary').text('Wikitoungues είναι κοινωνική προσπάθεια να δοθούν όλες οι 7.000 γλώσσες του κόσμου σε ολους τους ανθρώπους του κόσμου -- οι ιστορίες και τα συναισθύματα τους. Σε συνεργασία με δίκτυο εθελὀντες, είμαστε αφοσιομένοι να επιδείξουμε στον κόσμο το αληθινό νόημα πικιλίας.')
			$('.mobile-text').text('Wikitoungues είναι κοινωνική προσπάθεια να δοθούν όλες οι 7.000 γλώσσες του κόσμου σε ολους τους ανθρώπους του κόσμου -- οι ιστορίες και τα συναισθύματα τους. Σε συνεργασία με δίκτυο εθελὀντες, είμαστε αφοσιομένοι να επιδείξουμε στον κόσμο το αληθινό νόημα πικιλίας.')
			$('#get-involved').text('Πάρε μέρος.')
			$('.first').text('Φτιαγμένο με αγάπη από τη διεθνή ')
			$('.second').text(' και ')
			$('footer p:first-child').html('2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('όλα τα δικαιώματα κατοχυρωμένα.')
			$('#name').attr('placeholder','Τί είναι το ονομά σου;')
			$('#email').attr('placeholder','Τί είναι το email σου;')
			$('#message').attr('placeholder','Τί είναι το μηνυμά σου;')
			$('#submit').attr('value','Στειλε')
		} else if (activeLanguage === 'tiếng Việt') {
			$('.slogan').html('Mọi thứ tiếng trên thế giới, dành cho mọi người.')
			$('#summary').text('Wikitongues là một nỗ lực cộng đồng giúp cho tất cả mọi người của thế giới tiếp cận được với tất cả 7.000 ngôn ngữ của thế giới -- những câu chuyện và cảm giác phía sau chúng. Phối hợp với một mạng lưới những người tình nguyện, chúng tôi cam kết cho thế giới thấy ý nghĩa thực sự của sự đa dạng.')
			$('.mobile-text').text('Wikitongues là một nỗ lực cộng đồng giúp cho tất cả mọi người của thế giới tiếp cận được với tất cả 7.000 ngôn ngữ của thế giới -- những câu chuyện và cảm giác phía sau chúng. Phối hợp với một mạng lưới những người tình nguyện, chúng tôi cam kết cho thế giới thấy ý nghĩa thực sự của sự đa dạng.')
			$('#get-involved').text('Hãy tham gia.')
			$('.first').text('Được thực hiện với tình yêu quốc tế bởi ')
			$('.second').text(' và ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Nắm Giữ Tất Cả Tác Quyền.')
			$('#name').attr('placeholder','Tên bạn là gì?')
			$('#email').attr('placeholder','Địa chỉ email của bạn là gì?')
			$('#message').attr('placeholder','Tin nhắn của bạn là gì?')
			$('#submit').attr('value','Gửi')
		} else if (activeLanguage === 'Suomi') {
			$('.slogan').html('Jokainen kieli maailmassa – kaikille.')
			$('#summary').text('Wikitongues on yhteisö, jonka toimen tarkoituksena on antaa kaikille maailman ihmisille pääsy kaikkiin maailman 7 000 kieleen — tarinoihin ja tunteisiin niiden takana. Yhteistyössä vapaaehtoisen verkoston kanssa pyrimme näyttämään maailmalle diversiteetin todellisen merkityksen.')
			$('.mobile-text').text('Wikitongues on yhteisö, jonka toimen tarkoituksena on antaa kaikille maailman ihmisille pääsy kaikkiin maailman 7 000 kieleen — tarinoihin ja tunteisiin niiden takana. Yhteistyössä vapaaehtoisen verkoston kanssa pyrimme näyttämään maailmalle diversiteetin todellisen merkityksen.')
			$('#get-involved').text('Lähde mukaan.')
			$('.first').text('Luoneet kansainvälisellä rakkaudella ')
			$('.second').text(' ja ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Kaikki oikeudet pidätetään.')
			$('#name').attr('placeholder','"Mikä on sinun nimesi?')
			$('#email').attr('placeholder','Mikä on sähköpostiosoitteesi?')
			$('#message').attr('placeholder','Mikä on viestisi?')
			$('#submit').attr('value','Läheta')
		} else if (activeLanguage === 'Polski') {
			$('.slogan').html('Każdy język na świecie, dla każdego')
			$('#summary').text('Wikitounges to wynik wspólnej pracy, aby dać ludziom dostęp do wszystkich 7000 języków świata - historii i uczuć, które im towarzyszą. We współpracy z internetowymi wolontariuszami zdecydowaliśmy się pokazać światu prawdziwą definicję różnorodności.')
			$('.mobile-text').text('Wikitounges to wynik wspólnej pracy, aby dać ludziom dostęp do wszystkich 7000 języków świata - historii i uczuć, które im towarzyszą. We współpracy z internetowymi wolontariuszami zdecydowaliśmy się pokazać światu prawdziwą definicję różnorodności.')
			$('#get-involved').text('Zaangażuj się.')
			$('.first').text('Stworzone wraz z międzynarodową miłością przez ')
			$('.second').text(' i ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Wszystkie prawa zastrzeżone.')
			$('#name').attr('placeholder','Jak się nazywasz?')
			$('#email').attr('placeholder','Jaki jest twój email?')
			$('#message').attr('placeholder','Jaka jest twoja wiadomość?')
			$('#submit').attr('value','Wyślij')
		} else if (activeLanguage === 'Nederlands') {
			$('.slogan').html('Elke taal in de wereld, voor iedereen.')
			$('#summary').text('Wikitongues is een gemeenschappelijke inspanning om alle mensen van over de hele wereld toegang te geven tot 7000 talen - de verhalen en de gevoelens erachter. In samenwerking met een netwerk van vrijwilligers, zijn we ervan overtuigd de wereld te tonen wat de ware betekenis is van diversiteit.')
			$('.mobile-text').text('Wikitongues is een gemeenschappelijke inspanning om alle mensen van over de hele wereld toegang te geven tot 7000 talen - de verhalen en de gevoelens erachter. In samenwerking met een netwerk van vrijwilligers, zijn we ervan overtuigd de wereld te tonen wat de ware betekenis is van diversiteit.')
			$('#get-involved').text('Doe mee.')
			$('.first').text('Mogelijk gemaakt met internationale liefde van')
			$('.second').text(' en ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Alle Rechten Voorbehouden.')
			$('#name').attr('placeholder','Wat is uw naam?')
			$('#email').attr('placeholder','Wat is uw email?')
			$('#message').attr('placeholder','Wat is uw bericht?')
			$('#submit').attr('value','Verzenden')
		} else if (activeLanguage === 'Gaeilge') {
			$('.slogan').html('Gach teanga ar domhan, ar son cách.')
			$('#summary').text('Is tionscadal pobalbhunaithe é Wikitongues atá ag iarraidh gach ceann de na 7000 teanga ar domhan — agus na scéalta agus na mothúcháin atá iontu — a chur ar fáil do chách. I gcomhar le líonra mór saorálaithe, ba mhaith linn an éagsúlacht, agus an tábhacht a bhaineann léi, a chur ar taispeáint.')
			$('.mobile-text').text('Is tionscadal pobalbhunaithe é Wikitongues atá ag iarraidh gach ceann de na 7000 teanga ar domhan — agus na scéalta agus na mothúcháin atá iontu — a chur ar fáil do chách. I gcomhar le líonra mór saorálaithe, ba mhaith linn an éagsúlacht, agus an tábhacht a bhaineann léi, a chur ar taispeáint.')
			$('#get-involved').text('Glac páirt.')
			$('.first').text('Déanta le grá idirnáisiúnta ag ')
			$('.second').text(' agus ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Gach Ceart Ar Cosaint.')
			$('#name').attr('placeholder','Cad is ainm duit?')
			$('#email').attr('placeholder','ad é do sheoladh ríomhphoist?')
			$('#message').attr('placeholder','Cad é do theachtaireacht?')
			$('#submit').attr('value','Seol')
		} else if (activeLanguage === 'Français') {
			$('.slogan').html('Toutes les langues du monde, pour tout le monde.')
			$('#summary').text('Wikitongues est une entreprise collective ayant pour but l\'accès pour tous les gens du globe aux 7000 langues du monde, ainsi qu\'aux histoires et aux émotions derrière chacune d\'entre elles. Avec la collaboration d\'un réseau de volontaires, nous avons pour objectif de montrer au monde le vrai sens du mot diversité.')
			$('.mobile-text').text('Wikitongues est une entreprise collective ayant pour but l\'accès pour tous les gens du globe aux 7000 langues du monde, ainsi qu\'aux histoires et aux émotions derrière chacune d\'entre elles. Avec la collaboration d\'un réseau de volontaires, nous avons pour objectif de montrer au monde le vrai sens du mot diversité.')
			$('#get-involved').text('Impliquez-vous')
			$('.first').text('Fait avec l\'amour international de ')
			$('.second').text('et')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Tous Droits Réservés.')
			$('#name').attr('placeholder','Comment vous appelez-vous?')
			$('#email').attr('placeholder','Quelle est votre adresse mail?')
			$('#message').attr('placeholder','Quel est votre message?')
			$('#submit').attr('value','Envoyez')
		} else if (activeLanguage === 'Kernewek') {
			$('.slogan').html('Pub taves e\'n bes, rag pubonan.')
			$('#summary').text('Thew \'Wikitongues\' assay kevrednek neb a rei dhe bobel an norves fordh bera dhe seyth mil taves an bes - dhe\'n whedhlow ha dhe\'n omglowans war aga lergh. En cussulya gen rosweyth a vodhogyon, tho nei omres agan honan dhe dhisqwedhes dhe\'n bes styryans gwir an liesecter.')
			$('.mobile-text').text('Thew \'Wikitongues\' assay kevrednek neb a rei dhe bobel an norves fordh bera dhe seyth mil taves an bes - dhe\'n whedhlow ha dhe\'n omglowans war aga lergh. En cussulya gen rosweyth a vodhogyon, tho nei omres agan honan dhe dhisqwedhes dhe\'n bes styryans gwir an liesecter.')
			$('#get-involved').text('Mellyewgh ganjo!')
			$('.first').text('Gwres en kerenja geswlasek gen ')
			$('.second').text('ha')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Pub Gwir Gwithys.')
			$('#name').attr('placeholder','Pe hanow o\'whei?')
			$('#email').attr('placeholder','Pandr\'ew \'gas trigva e-bost?')
			$('#message').attr('placeholder','Pandr\'ew \'gas negejedh?')
			$('#submit').attr('value','Danon!')
		} else if (activeLanguage === 'English') {
			$('.slogan').html('Every language in the world, <span class="no-wrap">for everyone.</span>')
			$('#summary').text('Wikitongues is a community effort to give all the world’s people access to all the world’s 7,000 languages — the stories and the feelings behind them. In coordination with a network of volunteers, we\'re dedicated to showing the world the true meaning of diversity.')
			$('.mobile-text').text('Wikitongues is a community effort to give all the world’s people access to all the world’s 7,000 languages — the stories and the feelings behind them. In coordination with a network of volunteers, we\'re dedicated to showing the world the true meaning of diversity.')
			$('#get-involved').text('Get involved.')
			$('.first').text('Made with international love by')
			$('.second').text('and')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').html('All Rights Reserved.')
			$('#name').attr('placeholder','What\'s your name?')
			$('#email').attr('placeholder','What\'s your email?')
			$('#message').attr('placeholder','What\'s up?')
			$('#submit').attr('value','Send')
		} else if (activeLanguage === 'יידיש') {
			$('.slogan').html('יעדער לשון אויף דער װעלט, פאר אלע.')
			$('#summary').text('װיקיטאנגעס איז א ציבערדיקע אנשטרענגונג צו געבן אלע די מענטשן אויף דער װעלט צוטריט צו אלע די 7,000 לשונות אויף דער װעלט ־ די געשיכטעס און די פולונגן דערװעגן. אין תאום מיט א רשת פון בעלנים, מיר זענען געווידמעט צו ארויסװייזן די װעלט דער פשט פון פילפאלט.')
			$('.mobile-text').text('װיקיטאנגעס איז א ציבערדיקע אנשטרענגונג צו געבן אלע די מענטשן אויף דער װעלט צוטריט צו אלע די 7,000 לשונות אויף דער װעלט ־ די געשיכטעס און די פולונגן דערװעגן. אין תאום מיט א רשת פון בעלנים, מיר זענען געווידמעט צו ארויסװייזן די װעלט דער פשט פון פילפאלט.')
			$('#get-involved').text('זייט פארבונדן.')
			$('.first').text('געטאן מיט אינטערנאציאנאלע ליב פון @dbudell、')
			$('.second').text('און')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />װיקיטאנגעס.')
			$('footer p:last-child').text('אלע רעכטן געהאלטן.')
			$('#name').attr('placeholder','װאס הייסט איר?')
			$('#email').attr('placeholder','װאס איז איר בליצפאסט אדרעס?')
			$('#message').attr('placeholder','װאס איז איר אנזאג.')
			$('#submit').attr('value','שיקן')
		} else if (activeLanguage === '繁體中文') {
			$('.slogan').html('和大家分享世界上的每一種語言。')
			$('#summary').text('Wikitongues 是一個由社群經營，提供世界各地的人們了解 7,000 種語言背後的故事和看法。藉由和網路志工的合作，我們正向世界展示何謂多樣性的真實意義。')
			$('.mobile-text').text('Wikitongues 是一個由社群經營，提供世界各地的人們了解 7,000 種語言背後的故事和看法。藉由和網路志工的合作，我們正向世界展示何謂多樣性的真實意義。')
			$('#get-involved').text('成為我們的一份子。')
			$('.first').text('共同製作。')
			$('.second').text('以及')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('All Rights Reserved.')
			$('#name').attr('placeholder','您的大名')
			$('#email').attr('placeholder','電子郵件')
			$('#message').attr('placeholder','在這裡留言吧')
			$('#submit').attr('value','傳送')
		} else if (activeLanguage === 'Türkçe') {
			$('.slogan').html('Dünyadaki her dil, herkes için.')
			$('#summary').text('Wikitongues, dünya insanlarını dünyadaki 7000 dilin tamamına, onların hikayelerine ve duygularına ulaştırmayı amaçlayan bir topluluk girişimidir. Bir grup gönüllünün işbirliğiyle dünyaya, çeşitliliğin gerçek anlamını göstermeyi amaçlıyoruz.')
			$('.mobile-text').text('Wikitongues, dünya insanlarını dünyadaki 7000 dilin tamamına, onların hikayelerine ve duygularına ulaştırmayı amaçlayan bir topluluk girişimidir. Bir grup gönüllünün işbirliğiyle dünyaya, çeşitliliğin gerçek anlamını göstermeyi amaçlıyoruz.')
			$('#get-involved').text('Siz de katılın.')
			$('.first').text('dan uluslararası sevgilerle yaratıldı.')
			$('.second').text('ve')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Tüm Hakkı Saklıdır.')
			$('#name').attr('placeholder','İsminiz nedir?')
			$('#email').attr('placeholder','E-posta adresiniz nedir?')
			$('#message').attr('placeholder','Mesajınız nedir?')
			$('#submit').attr('value','Gönder')
		} else if (activeLanguage === 'монгол') {
			$('.slogan').html('Хүн төрөлхтний бүх хэл, тэдгээрийн хүн бүхэнд.')
			$('#summary').text('Wikitongues (Хэлний Вики) нь бүх дэлхийн хүн төрөлхтний хэрэглэдэг 7000 хэл яриаг хооронд нь холбон өөр хоорондийн түүх болон мэдрэмж зэргийг бусаддаа түгээх хүртээхэд зориулагдсан сайн дурынхны нэгдсэн сүлжээ юм. Бидний зорилго бол бусдад энэ дэлхийг бодитоор харахад туслахад оршино.')
			$('.mobile-text').text('Wikitongues (Хэлний Вики) нь бүх дэлхийн хүн төрөлхтний хэрэглэдэг 7000 хэл яриаг хооронд нь холбон өөр хоорондийн түүх болон мэдрэмж зэргийг бусаддаа түгээх хүртээхэд зориулагдсан сайн дурынхны нэгдсэн сүлжээ юм. Бидний зорилго бол бусдад энэ дэлхийг бодитоор харахад туслахад оршино.')
			$('#get-involved').text('Бидэнтэй нэгдэх.')
			$('.first').text('Санаачилагчид болох дэлхийн өнцөг бүрээс та бүхэнтэй мэндчилж буй ')
			$('.second').text('and')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Бүх эрх хуулиар хамгаалагдсан.')
			$('#name').attr('placeholder','Таны нэр хэн бэ?')
			$('#email').attr('placeholder','а и-мейл хаягаа оруулна уу?')
			$('#message').attr('placeholder','Та сэтгэгдэл?')
			$('#submit').attr('value','Илгээ')
		} else if (activeLanguage === 'Íslenska') {
			$('.slogan').html('Öll tungumál í heiminum, fyrir alla.')
			$('#summary').text('Wikitongues er félagsátak til að gefa öllu fólki heims aðgang að öllum 7\'000 tungumál heimsins - sögurnar og tilfinningarnar sem lyggja að baki. Í samhæfingu við sjálfboðaliðarneti tileinkum við okkur í að sýna heiminum alvöru merkingu fjölbreytileikans.')
			$('.mobile-text').text('Wikitongues er félagsátak til að gefa öllu fólki heims aðgang að öllum 7\'000 tungumál heimsins - sögurnar og tilfinningarnar sem lyggja að baki. Í samhæfingu við sjálfboðaliðarneti tileinkum við okkur í að sýna heiminum alvöru merkingu fjölbreytileikans.')
			$('#get-involved').text('Taktu þátt.')
			$('.first').text('Búið til með alþjóðalegri ást af ')
			$('.second').text(' og ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Allur Réttur Áskilinn.')
			$('#name').attr('placeholder','Hvað heitir þú?')
			$('#email').attr('placeholder','Hvað er netfangið þitt?')
			$('#message').attr('placeholder','Hver eru skilaboðin þín?')
			$('#submit').attr('value','Senda')
		} else if (activeLanguage === 'Eesti') {
			$('.slogan').html('Kõik keeled maailmas, kõigile.')
			$('#summary').text('Wikikeeled on ühiskondlik platvorm mis soovib tagada kõikidele liigipääsu maailma 7,000-le keelele, koos nendega seotud lugudele ja tunnetega. Koostöös vabatahtlike võrgustikuga me olme loodame näidata maailmale mitmekesisuse tõelist palet.')
			$('.mobile-text').text('Wikikeeled on ühiskondlik platvorm mis soovib tagada kõikidele liigipääsu maailma 7,000-le keelele, koos nendega seotud lugudele ja tunnetega. Koostöös vabatahtlike võrgustikuga me olme loodame näidata maailmale mitmekesisuse tõelist palet.')
			$('#get-involved').text('Hakka pihta!')
			$('.first').text('Rahvusvahelise armastusega ')
			$('.second').text(' ja ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Kõik õigused kaitstud.')
			$('#name').attr('placeholder','Mis su nimi on?')
			$('#email').attr('placeholder','Mis su email on?')
			$('#message').attr('placeholder','Mis su sõnum on?')
			$('#submit').attr('value','Saada')
		} else if (activeLanguage === 'Esperanto') {
			$('.slogan').html('Ĉiu lingvo de la mondo, por ĉiuj.')
			$('#summary').text('Wikitongues estas komunuma projeko celanta videbligi ĉiujn sepmil lingvojn de la mondo, kun ties rakontoj kaj sento, al ĉiuj popoloj de la mondo. Kunlabore kun reto de volontuloj, ni strebas montri al la mondo la veron de diverseco.')
			$('.mobile-text').text('Wikitongues estas komunuma projeko celanta videbligi ĉiujn sepmil lingvojn de la mondo, kun ties rakontoj kaj sento, al ĉiuj popoloj de la mondo. Kunlabore kun reto de volontuloj, ni strebas montri al la mondo la veron de diverseco.')
			$('#get-involved').text('Aliĝu')
			$('.first').text('Kun amo internacia faris ')
			$('.second').text(' kaj ')
			$('footer p:first-child').html('© 2014 ĉe <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Ĉiuj Rajtoj Rezervataj.')
			$('#name').attr('placeholder','Kiel vi nomiĝas?')
			$('#email').attr('placeholder','Kio estas via retadreso?')
			$('#message').attr('placeholder','Kio estas via mesaĝo?')
			$('#submit').attr('value','Sendi')
		} else if (activeLanguage === 'тарашкевіца') {
			$('.slogan').html('Кожная мова ў сьвеце, для ўсіх')
			$('#summary').text('Wikitongues з\'яўляецца вынікам калектыўнай працы, каб дадаць усім людзям у сьвеце доступa дa ўсіх сусьветных 7000 моў - іх апавяданній ды пачуццій. Ў каардынацыі з сеткай добраахвотнікаў, мы мусім паказаць сьвету праўдзівае значэнне разнастайнасьцi.')
			$('.mobile-text').text('Wikitongues з\'яўляецца вынікам калектыўнай працы, каб дадаць усім людзям у сьвеце доступa дa ўсіх сусьветных 7000 моў - іх апавяданній ды пачуццій. Ў каардынацыі з сеткай добраахвотнікаў, мы мусім паказаць сьвету праўдзівае значэнне разнастайнасьцi.')
			$('#get-involved').text('Прымай удзел.')
			$('.first').text('Зроблена з міжнароднай любоўю любоўю любоўю ')
			$('.second').text(' i ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('All Rights Reserved.')
			$('#name').attr('placeholder','Як вас зaвyць?')
			$('#email').attr('placeholder','Які ваш e-mail?')
			$('#message').attr('placeholder','Што ваша паведамленне?')
			$('#submit').attr('value','Паслаць')
		} else if (activeLanguage === 'Solresol') {
			$('.slogan').html('Sire solresol misisimi dodore, mido mifala.')
			$('#summary').text('Wikitongue faremi miredosol remila falaredo lamisolsi misolredo mimido famimi solresol fasi dodore – solsidofa re solrelafa midodosi dofa. solsidofa re solrelafa midodosi dofa, dore miremila lasolfado dodore dofasolsi simire lasi misoldosi.')
			$('.mobile-text').text('Wikitongue faremi miredosol remila falaredo lamisolsi misolredo mimido famimi solresol fasi dodore – solsidofa re solrelafa midodosi dofa. solsidofa re solrelafa midodosi dofa, dore miremila lasolfado dodore dofasolsi simire lasi misoldosi.')
			$('#get-involved').text('Domi dosido.')
			$('.first').text('Dodo fasolla midodsi sifamire milasi falami ')
			$('.second').text(' re ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Lamisolsi refasi fasifami.')
			$('#name').attr('placeholder','Remi resisolre?')
			$('#email').attr('placeholder','Remi fadomi solsilare?')
			$('#message').attr('placeholder','Remi lafala?')
			$('#submit').attr('value','Resolrefa lafala')
		} else if (activeLanguage === 'Galego') {
			$('.slogan').html('Todas as linguas do mundo, para todos.')
			$('#summary').text('Wikitongues é un proxecto de esforzo comunitario para que todas as persoas do mundo teñan acceso ás 7000 linguas que existen, ás súas historias e aos sentimentos que hai detrás delas. Coordinados a través dunha rede de voluntarios, dedicámonos a amosarlle ao mundo o verdadeiro significado da diversidade.')
			$('.mobile-text').text('Wikitongues é un proxecto de esforzo comunitario para que todas as persoas do mundo teñan acceso ás 7000 linguas que existen, ás súas historias e aos sentimentos que hai detrás delas. Coordinados a través dunha rede de voluntarios, dedicámonos a amosarlle ao mundo o verdadeiro significado da diversidade.')
			$('#get-involved').text('Implícate.')
			$('.first').text('Feito con amor internacional por')
			$('.second').text(' e ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Todos os dereitos reservados.')
			$('#name').attr('placeholder','Cal é o teu nome?')
			$('#email').attr('placeholder','Cal é o teu enderezo electrónico?')
			$('#message').attr('placeholder','Cal é a túa mensaxe?')
			$('#submit').attr('value','Enviar')
		} else if (activeLanguage === 'Български') {
			$('.slogan').html('Всеки език на света, за всички.')
			$('#summary').text('Wikitongues е колективен опит да се предостави достъп на всички хора в света до всичките 7 000 езика — тяхната история и чувствата им. Чрез съгласувана мрежа от доброволци, ние сме устремени да покажем на света истинското значение на разнообразието.')
			$('.mobile-text').text('Wikitongues е колективен опит да се предостави достъп на всички хора в света до всичките 7 000 езика — тяхната история и чувствата им. Чрез съгласувана мрежа от доброволци, ние сме устремени да покажем на света истинското значение на разнообразието.')
			$('#get-involved').text('Участвайте и Вие.')
			$('.first').text('Създадено с международната обич на ')
			$('.second').text(' and ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('всички права запазени.')
			$('#name').attr('placeholder','Какво е името Ви?')
			$('#email').attr('placeholder','Каква е е-пощата Ви?')
			$('#message').attr('placeholder','Какво е Вашето съобщение?')
			$('#submit').attr('value','Изпращане')
		} else if (activeLanguage === 'Latviešu') {
			$('.slogan').html('Katra valoda pasaulē, katram.')
			$('#summary').text('"Vikimēles" ir sabiedrības pūles lai dotu visas pasaules ļaudīm pieeju visas pasaules 7,000 valodām-stāstus un jūtas aiz viņiem. Saskaņojot ar tīklu no brīvprātīgajiem, mēs veltījām lai parādītu pasaulei daudzveidības patieso nozīmi.')
			$('.mobile-text').text('"Vikimēles" ir sabiedrības pūles lai dotu visas pasaules ļaudīm pieeju visas pasaules 7,000 valodām-stāstus un jūtas aiz viņiem. Saskaņojot ar tīklu no brīvprātīgajiem, mēs veltījām lai parādītu pasaulei daudzveidības patieso nozīmi.')
			$('#get-involved').text('Iesaisties.')
			$('.first').text('Izveidots ar starptautisku mīlestību ')
			$('.second').text(' un ')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Vikimēles.')
			$('footer p:last-child').text('Visas tiesības ir aizsargātas.')
			$('#name').attr('placeholder','Kā tevi sauc?')
			$('#email').attr('placeholder','Kāds ir tavs e-pasts?')
			$('#message').attr('placeholder','Kāds ir tavs vēstījums?')
			$('#submit').attr('value','Sūtīt.')
		} else if (activeLanguage === 'Lietuvių') {
			$('.slogan').text('Visos pasaulio kalbos - kiekvienam.')
			$('#summary').text('Wikitongues tai organizacija, siekianti suteikti žmonėms prieigą prie visų - 7000 pasaulio kalbų, jas išgirsti ir pajausti. Bendradarbiaujant su gausybę savanorių es dirbame tam, kad parodytume koks įvairus yra pasaulis.')
			$('.mobile-text').text('Wikitongues tai organizacija, siekianti suteikti žmonėms prieigą prie visų - 7000 pasaulio kalbų, jas išgirsti ir pajausti. Bendradarbiaujant su gausybę savanorių es dirbame tam, kad parodytume koks įvairus yra pasaulis.')
			$('#get-involved').text('Prisijunk ir Tu!')
			$('.first').text('Tarptautiškumą mylintys ')
			$('.second').text(' ir')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Visos teisės saugomos.')
			$('#name').attr('placeholder','Koks tavo vardas?')
			$('#email').attr('placeholder','Koks jūsų elektroninio pašto?')
			$('#message').attr('placeholder','Kaip reikalai?')
			$('#submit').attr('value','Siųsti')
		} else if (activeLanguage === 'Magyar') {
			$('.slogan').html('A vilàg minden nyelve, mindenkinek.')
			$('#summary').text('A Wikitongues egy közösségi kezdeményezés, amelynek célja, hogy vilàgszerte mindenki szàmàra hozzàférhetôvé tegye a létezô 7000 nyelvet - és a hozzàjuk kapcsolòdò történeteket és érzéseket. Mûködésünket önkénteshàlòzatunkra alapozva szeretnénk megmutatni a vilàgnak, mit is jelent igazàbòl a diverzitàs.')
			$('.mobile-text').text('A Wikitongues egy közösségi kezdeményezés, amelynek célja, hogy vilàgszerte mindenki szàmàra hozzàférhetôvé tegye a létezô 7000 nyelvet - és a hozzàjuk kapcsolòdò történeteket és érzéseket. Mûködésünket önkénteshàlòzatunkra alapozva szeretnénk megmutatni a vilàgnak, mit is jelent igazàbòl a diverzitàs.')
			$('#get-involved').text('Csatlakozz a kezdeményezéshez.')
			$('.first').text('Készìtette @dbudell @freddieandrade @lindiebee és @fateuser nemzetközi odaadàssal.')
			$('.second').text('')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Minden jog fenntartva')
			$('#name').attr('placeholder','Hogy hìvnak?')
			$('#email').attr('placeholder','Mi az e-mail cìmed?')
			$('#message').attr('placeholder','Mit üzensz?')
			$('#submit').attr('value','Küldés')
		} else if (activeLanguage === 'Shqip') {
			$('.slogan').html('Secila gjuhë e botës, për të gjithë.')
			$('#summary').text('Wikitongues është një përpjekje e përbashkët për t’ju dhënë të gjithë njerëzve të botës mundësinë për të pasur qasje në secilën prej 7000 gjuhëve të botës – storjet dhe ndjenjat prapa tyre. Në bashkpunim me një rrjet vullnetarësh, ne jemi të përkushtuar t’i tregojmë botës domethënien e vërtetë të diversitetit.')
			$('.mobile-text').text('Wikitongues është një përpjekje e përbashkët për t’ju dhënë të gjithë njerëzve të botës mundësinë për të pasur qasje në secilën prej 7000 gjuhëve të botës – storjet dhe ndjenjat prapa tyre. Në bashkpunim me një rrjet vullnetarësh, ne jemi të përkushtuar t’i tregojmë botës domethënien e vërtetë të diversitetit.')
			$('#get-involved').text('Përfshihu edhe ti!')
			$('.first').text('E bërë me dashuri ndërkombëtare nga')
			$('.second').text('')
			$('footer p:first-child').html('© 2014 <img src="img/wikitonguesLogoSquare.svg" alt="" />Wikitongues.')
			$('footer p:last-child').text('Të gjitha të drejtat e rezervuara.')
			$('#name').attr('placeholder','Si quheni?')
			$('#email').attr('placeholder','Cili është email-i juaj?')
			$('#message').attr('placeholder','Cila është porosia juaj?')
			$('#submit').attr('value','Dërgo')
		}


		else {
			alert("Woops! There seems to be something wrong with this translation! We'll be sure to fix it as soon as possible! Thank you for checking us out :)")
		}
	})
}
